### ISSUE TITLE
No Random fluctuation on NeuroML/LEMS simulation

### ISSUE THREAD

**Issue by JessyD** [OpenSourceBrain/MejiasEtAl2016#12]
Is the NeuroML/LEMS implementation using a random seed to generate `xi`? It seems that all simulations are generating the exact rate. Apart from the lack of deviation, we seem to get a similar overall behaviour on the analyis of the power spectrum of L23 for the NeuroML/LEMS simulation.

![intralaminar](https://user-images.githubusercontent.com/10345440/47576786-3e85f900-d93d-11e8-8066-f6366b77072b.png)

This image can be reproduced on the `dev_python` branch and calling `python GenerateNeuroMLlite.py -intralaminar`

@pgleeson

**Comment by pgleeson** [comment]
The Sim*.json file should be generated with the seed parameter, which propagates to the generated LEMS*.xml, see here: https://github.com/mbezaire/ca1/blob/development/NeuroML2/network/nmllite/Sim_IClamp_olm.json

This can be set in the sim = Simulation(...) call, potentially read in from a command line argument. 

See [here](https://github.com/mbezaire/ca1/blob/development/NeuroML2/network/nmllite/Sweep.py#L142) for some nmllite code that sets the seed, runs multiple simulations and generates plots of behaviour of the net across multiple parameters. You should be able to use the run_once method in [NeuroMLliteRunner](https://github.com/NeuroML/NeuroMLlite/blob/master/neuromllite/sweep/ParameterSweep.py#L476) to run & reload many simulations with different seeds...

**Comment by JessyD** [comment]
Thanks! 
I am [now](https://github.com/OpenSourceBrain/MejiasEtAl2016/commit/bdd04281931fdc49759f302085c3c80cf95dcb9f) creating a different Sim*.json file for each run of the simulation. 

Calling `python GenerateNeuroMLlite.py -intralaminar` now generates the plot:
![intralaminar](https://user-images.githubusercontent.com/10345440/47648311-90af6000-db71-11e8-9c97-b28eba20f46f.png)

**Comment by pgleeson** [comment]
Reproduced here. Looks good.

**Comment by pgleeson** [comment]
Looks like fixed
