### ISSUE TITLE
Update nml model to generate stdev correctly

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MejiasEtAl2016#3]
Should use tau, dt and stdev (dimensionless) to calculate noise current in [here](https://github.com/OpenSourceBrain/MejiasEtAl2016/blob/9c5d2f85a7daea471bc0469dc9b65443bf433b2d/NeuroML2/RateBased.xml#L65), based on [this](https://github.com/OpenSourceBrain/MejiasEtAl2016/blob/9c5d2f85a7daea471bc0469dc9b65443bf433b2d/Python/calculate_rate.py#L30).

**Comment by JessyD** [comment]
@pgleeson 

[Here](https://github.com/OpenSourceBrain/MejiasEtAl2016/commit/c21dcd1c5b85750977d4be2bccd4a708659954c0) I updated the stdev definition as defined on the paper.

Running the tests with
```
./run_tests.sh
python GenerateNeuroMLlite.py -test
```
![screen shot 2018-10-07 at 20 57 30](https://user-images.githubusercontent.com/10345440/46586299-71427d00-ca74-11e8-918f-ced607bcecaa.png)

**Comment by pgleeson** [comment]
Nice work. I'm getting an error though with the latest commit:
```
Traceback (most recent call last):
  File "GenerateNeuroMLlite.py", line 321, in <module>
    sim, net = generate()
  File "GenerateNeuroMLlite.py", line 90, in generate
    W = [[l2e_l2e, l2e_l2i, l2e_l5e, l2e_l5i],
NameError: global name 'l2e_l5e' is not defined

```

**Comment by pgleeson** [comment]
@JessyD As a quick test of my point about the noise magnitude depending on dt, try using a different value of dt in the LEMS_Test.xml. A 10 times smaller dt will lead to much smaller magnitude of noise...

**Comment by JessyD** [comment]
This issue have been fixed on https://github.com/OpenSourceBrain/MejiasEtAl2016/pull/11, the NeuroML/LEMS now scales the noise depending on `dt`. However, it is important to define the same [`noiseDt`](https://github.com/OpenSourceBrain/MejiasEtAl2016/blob/master/NeuroML2/Prototypes.xml#L4) as the [`dt`](https://github.com/OpenSourceBrain/MejiasEtAl2016/blob/dev_python/NeuroML2/GenerateNeuroMLlite.py#L8) passed to the simulation. 
![screen shot 2018-10-24 at 19 36 48](https://user-images.githubusercontent.com/10345440/47577540-0ed7f080-d93f-11e8-84c2-109fd1313ae9.png)


This is a quick test to show that the NeuroML/LEMS simulation is scaling by the noise:

To reproduce this call (in NeuroML):
``` 
./test_dt.sh 
 python GenerateNeuroMLlite.py -dt
```
